const destinasiWisata = [
  {
    id: 1,
    url: "/images/masjid-baiturrahman.png",
    tittle: "Masjid Raya Baiturrahman",
    desc: "Masjid Raya Baiturrahman adalah salah satu masjid yang ada di Desa Kampung Baru, Kecamatan Baiturrahman, Kota Banda Aceh. Masyarakat Aceh menggunakan masjid ini sebagai tempat ibadah dan syiar Islam. Masjid Raya Baiturrahman didirikan oleh Sultan Alauddin Mahmud Syah I pada tahun 1292 M. Tidak hanya merupakan tempat ibadah bagi umat Islam tetapi juga menjadi simbol yang kuat bagi agama, budaya, semangat, dan perjuangan rakyat Aceh. Dibangun pada tahun 1612 oleh Sultan Iskandar Muda, masjid ini telah mengalami banyak pemugaran, termasuk setelah gempa dan tsunami yang menghantam Aceh pada tahun 2004. Kubahnya yang hitam dengan diameter mencapai 35 meter, menyerupai Ka'bah di Mekkah, menjadi ciri khas yang ikonik. Sedangkan 7 menaranya melambangkan 7 lapisan langit dalam Islam, menambah keanggunan dan keunikan arsitektur masjid ini. Gabungan gaya arsitektur Mughal, Turki, dan Melayu memberikan Masjid Raya Baiturrahman karakter yang sangat khas. Ruangannya yang luas, terdiri dari ruang utama, serambi, dan halaman, mampu menampung hingga 9.000 jamaah, menjadikannya pusat kegiatan keagamaan yang vital bagi umat Islam di Aceh. Namun, tidak hanya sebagai tempat ibadah, masjid ini juga memegang peran penting sebagai simbol budaya, mencerminkan nilai-nilai Islam dan tradisi lokal Aceh. Selain itu, Masjid Raya Baiturrahman juga menjadi pusat pendidikan dan dakwah Islam, menyelenggarakan berbagai kegiatan untuk menyebarkan ajaran agama dan nilai-nilai kebaikan. Tak heran, masjid ini juga menjadi tujuan wisata religi yang populer bagi wisatawan lokal maupun mancanegara. Dengan keindahan arsitekturnya, sejarahnya yang panjang, dan perannya yang beragam, Masjid Raya Baiturrahman telah menjadi salah satu landmark paling terkenal dan dihormati di Indonesia, memberikan inspirasi dan kebanggaan bagi seluruh rakyat Aceh.",
    location: { lat: 5.5535711, lng: 95.3147101 },
    locate: "Kec. Baitussalam, Kab. Aceh Besar",
    typeLocation: "Masjid",
    typeSellTicket: "Gratis",
  },
  {
    id: 2,
    url: "/images/pulau-rubiah.png",
    tittle: "Pulau Rubiah",
    desc: "Pulau Rubiah adalah sebuah pulau kecil yang terletak di Sabang, Aceh. Pulau ini terkenal dengan keindahan bawah lautnya yang menjadi surga bagi para penyelam. Di sini, Anda bisa menemukan berbagai macam terumbu karang dan ikan-ikan tropis yang menakjubkan.",
    location: { lat: 5.8833454666027265, lng: 95.25749272220413 },
    locate: "Kec. Baitussalam, Kab. Aceh Besar",
    typeLocation: "Pantai",
    typeSellTicket: "Offline",
  },
  {
    id: 3,
    url: "/images/lauser-mount.png",
    tittle: "Taman Nasional Gunung Leuser",
    desc: "Taman Nasional Gunung Leuser adalah salah satu taman nasional terbesar di Indonesia yang terletak di provinsi Aceh dan Sumatera Utara. Taman ini merupakan habitat bagi berbagai spesies langka dan dilindungi, seperti orangutan Sumatera. Tempat ini sangat cocok bagi para pecinta alam dan petualang yang ingin menikmati keindahan alam yang luar biasa.",
    location: { lat: 3.769304872548158, lng: 97.1743388690795 },
    locate: "Kec. Kutapanjang, Kab. Gayo Lues",
    typeLocation: "Wisata Alam",
    typeSellTicket: "Online",
  },
  {
    id: 4,
    url: "/images/pantai-kuala-merisi.png",
    tittle: "Pantai Kuala Merisi",
    desc: "Pantai Kuala Merisi adalah destinasi wisata yang menawarkan pemandangan pantai yang indah dan suasana yang tenang. Pantai ini terkenal dengan pasir putihnya yang halus dan air laut yang jernih. Tempat ini sangat ideal untuk berjemur, berenang, atau sekadar bersantai menikmati pemandangan.",
    location: { lat: 4.629777791192914, lng: 95.59170234262041 },
    locate: "Desa Keutapang, Kec. Krueng Sabe",
    typeLocation: "Pantai",
    typeSellTicket: "Offline",
  },
  {
    id: 5,
    url: "/images/benteng.png",
    tittle: "Benteng Indra Patra",
    desc: "Benteng Indra Patra adalah sebuah benteng bersejarah yang terletak di Aceh Besar. Benteng ini dibangun pada masa kejayaan Kerajaan Aceh untuk melindungi wilayah dari serangan musuh. Selain nilai sejarahnya, benteng ini juga menawarkan pemandangan yang indah dan sering dijadikan tempat untuk mengambil foto.",
    location: { lat: 5.633995542532263, lng: 95.47125942447198 },
    locate: "Kec. Baitussalam, Kab. Aceh Besar",
    typeLocation: "Wisata Buatan",
    typeSellTicket: "Offline",
  },
  {
    id: 6,
    url: "/images/air-terjun.png",
    tittle: "Air Terjung Blang Kolam",
    desc: "Air Terjun Blang Kolam adalah air terjun yang terletak di tengah hutan yang asri di Aceh Utara. Air terjun ini memiliki ketinggian sekitar 75 meter dan dikelilingi oleh pemandangan alam yang menakjubkan. Tempat ini cocok untuk piknik keluarga atau sekadar menikmati keindahan alam dan ketenangan.",
    location: { lat: 5.097448971145209, lng: 97.0112574010999 },
    locate: "Kec. Kuta Makmur, Kab. Aceh Utara",
    typeLocation: "Air Terjun",
    typeSellTicket: "Gratis",
  },
  {
    id: 7,
    url: "/images/tugunol-km.png",
    tittle: "Tugu Nol Kilometer",
    desc: "Tugu Nol Kilometer adalah sebuah monumen yang menandai titik awal perhitungan jarak di Indonesia. Terletak di ujung paling barat Indonesia, tepatnya di Kota Sabang, tugu ini menjadi destinasi populer bagi wisatawan yang ingin merasakan sensasi berada di titik nol kilometer Indonesia.",
    location: { lat: 5.582657670326205, lng: 95.31414037120999 },
    locate: "Desa Iboih, Kec. Sukakarya, Kota Sabang",
    typeLocation: "Wisata Buatan",
    typeSellTicket: "Offline",
  },
  {
    id: 8,
    url: "/images/museum-tsunami.png",
    tittle: "Museum Tsunami",
    desc: "Museum Tsunami di Banda Aceh didirikan untuk mengenang peristiwa gempa bumi dan tsunami yang melanda Aceh pada tahun 2004. Museum ini menampilkan berbagai pameran tentang kejadian tersebut, termasuk foto, artefak, dan simulasi yang memberikan pemahaman mendalam tentang bencana dan upaya pemulihan yang dilakukan. Selain sebagai tempat edukasi, museum ini juga berfungsi sebagai pusat mitigasi bencana.",
    location: { lat: 5.547729427749161, lng: 95.31519163497387 },
    locate: "Kec. Baiturrahman, Kota Banda Aceh",
    typeLocation: "Wisata Buatan",
    typeSellTicket: "Online",
  },
  {
    id: 9,
    url: "/images/lampuuk-beach.png",
    tittle: "Pantai Lampuuk",
    desc: "Pantai Lampuuk adalah salah satu pantai terindah di Aceh dengan pasir putih yang lembut dan air laut yang biru jernih. Pantai ini juga terkenal sebagai tempat berselancar dan memiliki pemandangan matahari terbenam yang menakjubkan. Selain itu, di sekitar pantai terdapat banyak warung yang menyajikan hidangan laut segar.",
    location: { lat: 5.4854817559748685, lng: 95.22646744063586 },
    locate: "Kec. Baiturrahman, Kota Banda Aceh",
    typeLocation: "Pantai",
    typeSellTicket: "Offline",
  },
];

export default destinasiWisata;
