const destinasiWisata = [
  {
    id: 1,
    url: "/images/mie-aceh.png",
    tittle: "Masjid Raya Baiturrahman",
    location: "Kec. Baiturrahman, Kota Banda Aceh",
    typeLocation: "Masjid",
    typeSellTicket: "Gratis",
  },
  {
    id: 2,
    url: "/images/pulau-rubiah.png",
    tittle: "Pulau Rubiah",
    location: "Desa Iboih, Kec. Sukakarya, Kota Sabang",
    typeLocation: "Pantai",
    typeSellTicket: "Offline",
  },
  {
    id: 3,
    url: "/images/mie-aceh.png",
    tittle: "Tugu Nol Kilometer",
    location: "Desa Iboih, Kec. Sukakarya, Kota Sabang",
    typeLocation: "Wisata Buatan",
    typeSellTicket: "Offline",
  },
  {
    id: 4,
    url: "/images/museum-tsunami.png",
    tittle: "Museum Tsunami",
    location: "Kec. Baiturrahman, Kota Banda Aceh",
    typeLocation: "Wisata Buatan",
    typeSellTicket: "Online",
  },
  {
    id: 5,
    url: "/images/lampuuk-beach.png",
    tittle: "Pantai Lampuuk",
    location: "Kec. Baiturrahman, Kota Banda Aceh",
    typeLocation: "Pantai",
    typeSellTicket: "Offline",
  },
  {
    id: 6,
    url: "/images/mie-aceh.png",
    tittle: "Air Terjung Blang Kolam",
    location: "Kec. Kuta Makmur, Kab. Aceh Utara",
    typeLocation: "Air Terjun",
    typeSellTicket: "Gratis",
  },
  {
    id: 7,
    url: "/images/mie-aceh.png",
    tittle: "Pantai Kuala Merisi",
    location: "Desa Keutapang, Kec. Krueng Sabe",
    typeLocation: "Pantai",
    typeSellTicket: "Offline",
  },
  {
    id: 8,
    url: "/images/gunung-lauser.png",
    tittle: "Taman Nasional Gunung Leuser",
    location: "Kec. Kutapanjang, Kab. Gayo Lues",
    typeLocation: "Wisata Alam",
    typeSellTicket: "Online",
  },
  {
    id: 9,
    url: "/images/mie-aceh.png",
    tittle: "Benteng Indra Patra",
    location: "Kec. Baitussalam, Kab. Aceh Besar",
    typeLocation: "Wisata Buatan",
    typeSellTicket: "Offline",
  },
];

export default destinasiWisata;
